name: Coveralls

on:
  push:
    branches:
      - master

jobs:
  coveralls:
    runs-on: ubuntu-latest

    steps:
      - name: Chckput code
        uses: action/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests with Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: npx test
